version: 2

updates:
  - package-ecosystem: nuget
    directories:
      - "/src/MaterialSymbols.Maui/*"
      - "/examples/MaterialSymbols.Maui.Demo/*"
    schedule:
      interval: weekly
      day: sunday
      time: "08:00"
      timezone: Europe/Berlin

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: "08:00"
      timezone: Europe/Berlin
