from __future__ import annotations

import argparse
import hashlib
import re
import tempfile
import urllib.request
from pathlib import Path

from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont


UPSTREAM_COMMIT = "50f0603134ce7b70b2d71b686cc13e8b57ccb74c"
UPSTREAM_BASE = (
    f"https://raw.githubusercontent.com/google/material-design-icons/{UPSTREAM_COMMIT}"
)
ASSETS = {
    "MaterialSymbolsOutlined[FILL,GRAD,opsz,wght].ttf": (
        "variablefont/MaterialSymbolsOutlined%5BFILL%2CGRAD%2Copsz%2Cwght%5D.ttf",
        "203967e6af26398682a48fa7b972c103d972632848411fb625a13de6e7838680",
    ),
    "MaterialSymbolsRounded[FILL,GRAD,opsz,wght].ttf": (
        "variablefont/MaterialSymbolsRounded%5BFILL%2CGRAD%2Copsz%2Cwght%5D.ttf",
        "619eaa2f2e270723cf0cd06d2aba126ade66fee94e380c3e6a61e2e496279e0c",
    ),
    "MaterialSymbolsSharp[FILL,GRAD,opsz,wght].ttf": (
        "variablefont/MaterialSymbolsSharp%5BFILL%2CGRAD%2Copsz%2Cwght%5D.ttf",
        "c8256273389905acf10714eef150653053df3ff8659ff351207eba5e784ca3bc",
    ),
    "MaterialSymbolsOutlined[FILL,GRAD,opsz,wght].codepoints": (
        "variablefont/MaterialSymbolsOutlined%5BFILL%2CGRAD%2Copsz%2Cwght%5D.codepoints",
        "a949567431829ed6f382911f3e6d3158627a4a5027d7e6f3d89a85a55c027279",
    ),
}


def download_assets(destination: Path) -> dict[str, Path]:
    paths: dict[str, Path] = {}
    for name, (relative_url, expected_hash) in ASSETS.items():
        path = destination / name
        urllib.request.urlretrieve(f"{UPSTREAM_BASE}/{relative_url}", path)
        actual_hash = hashlib.sha256(path.read_bytes()).hexdigest()
        if actual_hash != expected_hash:
            raise RuntimeError(f"SHA-256 mismatch for {name}: {actual_hash}")
        paths[name] = path
    return paths


def set_font_names(font: TTFont, family: str) -> None:
    name_table = font["name"]
    postscript_name = family.replace(" ", "")
    replacements = {
        1: family,
        2: "Regular",
        3: f"MaterialSymbols.Maui:{postscript_name}:2026",
        4: family,
        6: postscript_name,
        16: family,
        17: "Regular",
    }
    for name_id, value in replacements.items():
        name_table.setName(value, name_id, 3, 1, 0x0409)
        name_table.setName(value, name_id, 1, 0, 0)


def generate_font(source: Path, destination: Path, family: str, fill: int) -> None:
    variable_font = TTFont(source)
    static_font = instantiateVariableFont(
        variable_font,
        {"FILL": fill, "GRAD": 0, "opsz": 24, "wght": 400},
        inplace=False,
        optimize=True,
    )
    set_font_names(static_font, family)
    static_font.save(destination, reorderTables=True)


def validate_font(path: Path, expected_codepoints: set[int]) -> None:
    font = TTFont(path)
    if "fvar" in font:
        raise RuntimeError(f"Generated font is still variable: {path.name}")
    missing = expected_codepoints.difference(font.getBestCmap())
    if missing:
        preview = ", ".join(f"U+{codepoint:04X}" for codepoint in sorted(missing)[:10])
        raise RuntimeError(f"Generated font {path.name} is missing: {preview}")


def to_identifier(name: str) -> str:
    parts = [part for part in re.split(r"[^a-zA-Z0-9]+", name) if part]
    identifier_parts: list[str] = []
    for part in parts:
        segments = re.findall(r"[a-zA-Z]+|[0-9]+", part)
        identifier_parts.extend(
            segment if segment.isdigit() else segment[:1].upper() + segment[1:]
            for segment in segments
        )
    identifier = "".join(identifier_parts)
    if not identifier or identifier[0].isdigit():
        identifier = f"Icon{identifier}"
    return identifier


def generate_enum(codepoints: Path, destination: Path) -> int:
    members: list[tuple[str, str, int]] = []
    identifiers: dict[str, str] = {}
    for line in codepoints.read_text(encoding="utf-8").splitlines():
        upstream_name, hexadecimal = line.split()
        identifier = to_identifier(upstream_name)
        if previous := identifiers.get(identifier):
            raise RuntimeError(
                f"C# identifier collision: {previous!r} and {upstream_name!r} -> {identifier}"
            )
        identifiers[identifier] = upstream_name
        members.append((identifier, upstream_name, int(hexadecimal, 16)))

    lines = [
        "// <auto-generated />",
        f"// Google Material Symbols, upstream commit {UPSTREAM_COMMIT}.",
        "namespace MaterialSymbols.Maui;",
        "",
        "/// <summary>Names and Unicode codepoints from Google Material Symbols.</summary>",
        "public enum MaterialSymbol",
        "{",
        "    None = 0,",
    ]
    for identifier, upstream_name, codepoint in members:
        lines.append(f"    {identifier} = 0x{codepoint:X}, // {upstream_name}")
    lines.extend(["}", ""])
    destination.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    return len(members)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--project-root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
    )
    args = parser.parse_args()
    project_root = args.project_root.resolve()
    fonts_directory = project_root / "Resources" / "Fonts"
    fonts_directory.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory(prefix="material-symbols-maui-") as temporary:
        assets = download_assets(Path(temporary))
        for variant in ("Outlined", "Rounded", "Sharp"):
            source = assets[f"MaterialSymbols{variant}[FILL,GRAD,opsz,wght].ttf"]
            for filled in (False, True):
                suffix = "Filled" if filled else ""
                family = f"Material Symbols {variant}{' Filled' if filled else ''}"
                output = fonts_directory / f"MaterialSymbols{variant}{suffix}-Regular.ttf"
                generate_font(source, output, family, int(filled))

        codepoints_path = assets[
            "MaterialSymbolsOutlined[FILL,GRAD,opsz,wght].codepoints"
        ]
        expected_codepoints = {
            int(line.split()[1], 16)
            for line in codepoints_path.read_text(encoding="utf-8").splitlines()
        }
        for font_path in fonts_directory.glob("MaterialSymbols*-Regular.ttf"):
            validate_font(font_path, expected_codepoints)

        count = generate_enum(
            codepoints_path,
            project_root / "MaterialSymbol.cs",
        )

    print(f"Generated six fonts and {count} named symbols from {UPSTREAM_COMMIT}.")


if __name__ == "__main__":
    main()
